<article>
	<h2>Hej</h2>
	<?php
		print_r($_GET);
	?>
	<br><br><br><br><br><br><br><br><br><br>
	banan
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	kokosnöt
</article>
<article>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	mango
	<br><br><br><br><br><br>
	Sluuuuuut!
</aritcle>